#! /bin/sh

####2D common offset prestack time migration
# set parameter
indata=232.su
path=/home/CY/输入道倾角偏移/单偏移距
vfile=vrmstsh
kjfile1=kjmin
kjfile2=kjmax
parfile=fdmodpardata.dat
outdata=232srdmt.su
verbose=1

#excute migration
./srdmigD<$indata path=$path vfile=$vfile kjfile1=$kjfile1 kjfile2=$kjfile2 parfile=$parfile verbose=$verbose >$outdata

#display result
suximage<$outdata perc=99.8&

exit
